### ISSUE TITLE
Error downloading files

### ISSUE THREAD

**Issue by tuzzmaniandevil** [allejok96/jw-scripts#16]
This only seems to be a recent error.
Running on Ubuntu 18.04
Python 3.6.6
curl 7.58.0

Here is the command:
`jwb-index --mode filesystem --download`

And the stack trace:
```python
Traceback (most recent call last):
  File "/usr/local/bin/jwb-index", line 4, in <module>
    __import__('pkg_resources').run_script('jw-scripts==1.0', 'jwb-index')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/jw_scripts-1.0-py3.6.egg/EGG-INFO/scripts/jwb-index", line 102, in <module>
  File "/usr/local/lib/python3.6/dist-packages/jw_scripts-1.0-py3.6.egg/jwlib/output.py", line 162, in output_filesystem
FileNotFoundError: [Errno 2] No such file or directory: '../bhat_E_r720P.mp4' -> './jwb-E/VODMinistryExpandMinistry/Be Honest in All Things (Bethel/Construction Application).mp4'
```

The dir `./jwb-E/VODMinistryExpandMinistry/` is empty

**Comment by allejok96** [comment]
Ah I think it's the slash in the title of the video that mess things up... I'll try and fix that in a couple of days, as I'm out and about at the moment.

**Comment by tuzzmaniandevil** [comment]
Yea probably, thats for looking into it :-)

**Comment by allejok96** [comment]
Fixed the problem with slashes... also added the `--ntfs` flag that removes stuff like |<>:? if that even is a problem, I don't know... I don't have a windows install to test it on, so I'm just guessing :)

**Comment by tuzzmaniandevil** [comment]
@allejok96 Works perfectly on Linux now thanks :-)
