### ISSUE TITLE
Using on Windows

### ISSUE THREAD

**Issue by lukefarr** [allejok96/jw-scripts#7]
Dear Brothers:

Sorry to be a pain but I am trying to get this working for an elderly brother in my hall. My plan is to download all the content and he can watch it on a loop in Kodi.

I have tried the instructions on Windows installation and have tried the sample text to download all Children videos but get the following errors:

downloading: pksjj_E_054_r720P.mp4 (Song 054 "This Is the Way")
Traceback (most recent call last):
  File "jwb-index", line 71, in <module>
    jwb.download_all(os.path.join(wd, subdir))
  File "C:\JWtv\jw-scripts\jwlib\parse.py", line 322, in download_all
    media.file = self.download_media(media, wd)
  File "C:\JWtv\jw-scripts\jwlib\parse.py", line 284, in download_media
    _curl(media.url, file + '.part', rate_limit=self.rate_limit)
  File "C:\JWtv\jw-scripts\jwlib\parse.py", line 422, in _curl
    subprocess.call(proc, stderr=stderr)
  File "C:\Users\luke\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\luke\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\luke\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Any idea what I have done wrong?

**Comment by allejok96** [comment]
I haven't looked into it yet, but it looks like curl cannot be found...

**Comment by allejok96** [comment]
What version of Windows are you on?

**Comment by allejok96** [comment]
I've done some changes to make it easier to get working on Windows. Look at the page about installation on Win again... Have tested on Win 10. Let me know how it goes!

P.S. If your Kodi box is a Linux rig, checkout jwb-rpi... 😉

**Comment by lukefarr** [comment]
Windows 10.

New instructions worked great. Thanks so much.
